name: f_maps_firestore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter  
  flutter_json: ^0.0.2
  google_maps_flutter: ^2.5.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.6
  location: ^5.0.3
  provider: ^6.1.1
  toast: ^0.3.0
  webfeed: ^0.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/productlist.json
    - assets/imagen_usuario.jpg
