// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWGke_fp46fRGcUqdlZdMP1HuHsY5LWM',
    appId: '1:814177918884:web:87ae16d5bb11bd65edab31',
    messagingSenderId: '814177918884',
    projectId: 'findyourfood-405618',
    authDomain: 'findyourfood-405618.firebaseapp.com',
    storageBucket: 'findyourfood-405618.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxhdgC-C01LU5SnCPQcp35ptHSd10QeZI',
    appId: '1:814177918884:android:6cc83d86b32a3e77edab31',
    messagingSenderId: '814177918884',
    projectId: 'findyourfood-405618',
    storageBucket: 'findyourfood-405618.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNw7Hx_JpQKNaGr8gTCDcSKYIvuVcGsqM',
    appId: '1:814177918884:ios:09130a80f9be5837edab31',
    messagingSenderId: '814177918884',
    projectId: 'findyourfood-405618',
    storageBucket: 'findyourfood-405618.appspot.com',
    iosBundleId: 'com.example.fMapsFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNw7Hx_JpQKNaGr8gTCDcSKYIvuVcGsqM',
    appId: '1:814177918884:ios:cc8499494a78c113edab31',
    messagingSenderId: '814177918884',
    projectId: 'findyourfood-405618',
    storageBucket: 'findyourfood-405618.appspot.com',
    iosBundleId: 'com.example.fMapsFirestore.RunnerTests',
  );
}
